app: stripe-web-hooks
service: handler

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256

  stage: dev
  region: ap-southeast-2
  endpointType: EDGE
  logs: # Enable CloudWatch logs
    restApi: true
  # tracing: # Enable X-Ray tracing
  #   apiGateway: true'
  environment:
    STRIPE_SECRET_KEY: sk_test_6gXaKAsTbZTtk2HfiWTqjkrd
    STRIPE_WEBHOOKS_SECRET_KEY: whsec_q8n4wrOUwZT0HCg7XqJhHgn5zrQ6vOAu

custom:
  base: ${self:app}-${self:provider.stage}
functions:
  stripe-webhook:
    handler: handler.stripeWebhook
    name: ${self:custom.base}-handler
    description: deploy to ${self:provider.region} from local
    events:
      - http:
          path: stripe/webhook
          method: post
          async: false
