service: stripe-eventbridge
frameworkVersion: '>=1.54.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256

  stage: dev
  region: ap-southeast-2
  endpointType: EDGE
  logs: # Enable CloudWatch logs
    restApi: true
  tracing: # Enable X-Ray tracing
    apiGateway: true

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: '${cf:stripe-eventbridge-deps-${self:provider.stage}.StripeWebhookSecretArn}'
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: ${cf:stripe-eventbridge-deps-${self:provider.stage}.SNSTargetForFailedEvents}
    - Effect: 'Allow'
      Action:
        - 'events:PutEvents'
      Resource: '*'
custom:
  base: st-web-saas-${self:provider.stage}
functions:
  stripe-webhook:
    handler: handler.stripeWebhook
    events:
      - http:
          path: stripe/webhook
          method: post
          async: false
    environment:
      FAILURE_SNS:
        Fn::ImportValue: ${self:custom.base}-SNSTargetForFailedEvents
      EVENT_BRIDGE: 'default'
      ENDPOINT_SECRET:
        Fn::ImportValue: ${self:custom.base}-StripeWebhookSecret
